### ISSUE TITLE
doc : 요구사항

### ISSUE THREAD

**Issue by kimhanui** [kimhanui/URL-Shortener#8]
- [x] 웹 페이지 입력폼에 URL 입력 시 단축된 결과 출력  => #4 

- [x] 브라우저의 주소창에 단축 URL 입력 시 기존 URL로 리다이렉트 => #5 

- [x] 같은 URL 입력 시 동일한 결과값 도출 => #4 

- [x] 결과값은 주소를 제외하고 8글자 이내로 생성

**Comment by kimhanui** [comment]
### 결과값은 주소를 제외하고 8글자 이내로 생성
* pk 값을 Base-62 encode 했을 때 8글자 이내로 나오려면 가능한 pk 범위는?
    ```
    long 범위 : (unsigned일 때 ) 0~2^64-1
    ㄴ 최대값을 62로 나눠보면 8번 이상 나눠짐. 즉, 8자 이내로 생성하려면 long보다 작은 범위 사용해야한다.
    ```
    ```
    int 범위 : (unsigned일 때) 0~2^32-1
    ㄴ 최대값을 62로 나눠보면 5번까지 가능, 6번나누면 0 이하 숫자가 됨. 즉, int는  적합!
    ```

즉, 내 방식대로 하면 pk 자료형을 int로 하던가, long범위를 쓰되 encode했을 때 8자까지만 나오게 제한해야한다.

참고로 **Base-62 encode된 8자리를 가지는 최대 정수는 32214113938755** 이다.
